[project]
name = "qgss-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "qiskit>=2.1.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
